### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by 9il** [libmir/blog#34]
@ljubobratovicrelja Could you please update links and code in you blogs. The code requires to remove `nd` prefix and maybe other fixes.

**Comment by ljubobratovicrelja** [comment]
> Could you please update links and code in you blogs

Hey @9il,  sure thing.

@wilzbach I'm trying to start the server on my machine and keep getting this error:

```
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem bundler (>= 0.a) (Gem::GemNotFoundException)
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems.rb:258:in `bin_path'
	from /usr/local/bin/bundle:22:in `<main>'
```

I've tried all sorts of stuff - re-cloned the blog repo, reinstalled the ruby stuff via homebrew, reinstalled jekyll via gem, also tried some stuff I've found on the web browsing for a solution but haven't found any. Could you help me please?

**Comment by wilzbach** [comment]
Have you tried `gem install bundler`?
What commands are you running?

**Comment by ljubobratovicrelja** [comment]
> Have you tried gem install bundler?

I just have, and It works - thanks! :)
